### ISSUE TITLE
[THEORY] Implementing Mass Deletion

### ISSUE THREAD

**Issue by Stetsed** [sreedevk/pocketbase-sdk-rust#21]
So I was looking through the API of PocketBase and it seems right now it's not possible to delete a bunch of records with a certain filter. So what I suspect the only way to implement bulk operations would be to first query the database with the search, and then run through all ID's given and delete those one by one. This could be done relativley quickly though if we implement this to be async.

What do you think about this idear? If you do not see any problems with it I might try and take a shot at implementing it

**Comment by sreedevk** [comment]
@Stetsed I did consider doing something like this (using rayon) since you had mentioned this as a requirement before. But here's my thought:

Imagine deleting a million rows, you'll basically be making a million+ API calls. Since pocketbase itself doesn't support this, I think it'd make more sense for the application using this library to implement this. The pocketbase SDK itself should just be a layer over the existing API interface provided by pocketbase.

Let me know your thoughts.

**Comment by Stetsed** [comment]
@sreedevk I honestly agree, you could make a simple for loop to just delete all entries which wouldn't add a lot of code complexity to people writing code.

Prob wanna add a section to do to do which is like "Waiting for Upstream Implementation" which are features that aren't possible yet because there not possible upstream yet
